new-session  

# Allow mouse to select windows
set -g mouse on

# Use C-a
unbind C-b
set -g prefix C-a
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:RGB,*256col*:Tc"
set -as terminal-overrides ",*:sitm=\\E[3m,ritm=\\E[23m"
set -g xterm-keys on
set -g allow-rename on
set -g extended-keys on
set -g extended-keys-format csi-u
bind a send-prefix
bind-key -T root KPEnter send-keys Escape O M

set-window-option -g mode-keys vi

# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy), just like Vim
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Update the default binding of 'Enter' to use copy-selection-and-cancel
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# Reduce delay when pressing Escape in Vim
set -sg escape-time 10

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @plugin 'thalesmello/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/green'

run -b '~/.tmux/plugins/tpm/tpm'
